#!/usr/bin/env sh


# assert we are root
if [ ! "$UID" = "0" ]
then
    echo "Must be root"
    exit 1
fi

# go to script root
cd "$(readlink -f "$0")"

# copy fastread to /usr/local/bin
cp fastread /usr/local/bin/fastread

# print success message
echo "fastread successfully installed."
