#!/usr/bin/env sh


# assert we are root
if ! [ "$(id -u)" = "0" ]
then
    echo "must be root"
    exit 1
fi

# go to script dir
script_path="$(readlink -f "$0")"
script_dir="${script_path%/*}"
cd "$script_dir"

# copy fastread to /usr/local/bin
cp fastread /usr/local/bin/fastread

# print success message
echo "fastread successfully installed."
